### PR TITLE
Draft: Migrate null safety

### PR DESCRIPTION
**Pull request by acoutts**
Migrates to null safety but it's pending on a few open upstream PRs:
* https://github.com/aloisdeniel/http_extensions/pull/7
* ~~https://github.com/appsup-dart/x509/pull/9~~
* ~~https://github.com/appsup-dart/crypto_keys/pull/5~~

@rbellens can you please help on this one as well? A number of tests are now failing.

### CODE REVIEW

**Comment by acoutts** [comment]
@rbellens thanks for your work migrating those 2 other packages!! Unfortunately I am worried `http_extension` might not be maintained now. The las commit is 2 years ago and there's multiple open issues/PRs. I have an open PR there which migrates it and all of its sub packages to null safety: https://github.com/aloisdeniel/http_extensions/pull/7

Is it possible we can remove `jose`'s dependency on `http_extensions`, or if I hosted an updated `http_extensions` on pub would you be open to using that?

**Comment by acoutts** [comment]
@rbellens good news- I got all tests passing!! I had to push an update to `http_extensions_cache` to make sure `MemoryCacheStore` returns a nullable `CachedResponse?` and remove the casting overrides in the jose test for jwk.

Now we just need @aloisdeniel to merge/publish my PR at https://github.com/aloisdeniel/http_extensions/pull/7 and we can get jose published with the null safety migration here.

**Comment by rbellens** [comment]
It indeed seems that `http_extensions` is not maintained anymore. I'll remove the dependency.

**Comment by rbellens** [comment]
@acoutts thanks for all the pull requests. Helps a lot.

**Comment by aloisdeniel** [comment]
Thanks for the work.

I'll review that!

**Pull request merged**
